
-- Stored procedure pattern 

BEGIN TRY
    BEGIN TRANSACTION;
    -- DO STUFF
    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    DECLARE @ERRORMESSAGE NVARCHAR(MAX), 
        @ERRORSEVERITY INT, 
        @ERRORSTATE INT;
    SELECT @ERRORMESSAGE = ERROR_MESSAGE() + ' LINE ' + CAST(ERROR_LINE() AS NVARCHAR(5)), @ERRORSEVERITY = ERROR_SEVERITY(), @ERRORSTATE = ERROR_STATE();
    IF @@TRANCOUNT > 0
        ROLLBACK TRANSACTION;
    RAISERROR (@ERRORMESSAGE, @ERRORSEVERITY, @ERRORSTATE);
END CATCH
